🔧 Token Transformer 세팅 변경
sendOwlOrganization/mlab-web pull request #19
Opened 2023-05-18 12:14 UTC by ixio0330

## 변경 내용

- npx로 반복 실행하던 작업을 node로 실행하도록 수정
- light, dark 등 테마 토큰 추출 시 잘못된 설정 수정

## 체크리스트

- [ ] 백엔드 선배포
- [ ] Playwright 테스트 케이스 작성
- [ ] Jest Hook 테스트 케이스 작성
- [ ] Storybook 테스트 케이스 작성

## 📸 스크린샷

## 기타사항

---------------------------------------

## 🤚🏻 코드리뷰 하는 방법
🪧 [개발 공통 코드리뷰 가이드]

### ✎ Code Review Manner
1. **지적이 아닌 질문**하기
    - 원작하신분이 몰라서 그렇게 한게 아니라 그랬을 수 밖에 없는 상황일 수 있습니다
    - 위험하다고 판단시 _request change_
2. 다른 방법에 대해 **제안**하기
    - 이 때 본인이 생각한 것과 너무 다른 경우 _request change_
3. **예시코드를 작성**하여 댓글로 달기
4. 리뷰 마무리
    - 무플 방지! 고생한 사우에게 고생했다 한마디 남기는 게 좋습니다 (LGTM 강추)

### ✎ [Pn Rule](https://blog.banksalad.com/tech/banksalad-code-review-culture/#%EC%BB%A4%EB%AE%A4%EB%8B%88%EC%BC%80%EC%9D%B4%EC%85%98-%EB%B9%84%EC%9A%A9%EC%9D%84-%EC%A4%84%EC%9D%B4%EA%B8%B0-%EC%9C%84%ED%95%9C-pn-%EB%A3%B0)

- Pn
    - _**P1**_ : 꼭 반영해주세요 (Request changes)
    - _**P2**_ : 적극적으로 고려해주세요 (Request changes)
    - _**P3**_ : 웬만하면 반영해 주세요 (Comment)
    - _**P4**_ : 반영해도 좋고 넘어가도 좋습니다 (Approve)
    - _**P5**_ : 그냥 사소한 의견입니다 (Approve)

- Pn Resolve
    - P1, P2, P3는 리뷰어가 Resolve 합니다
    - P4, P5는 리뷰어가 아니더라도 Resolve 할 수 있습니다
    - Pn 표시가 없을 경우 P5로 봅니다

### ✎ PR Title Rule
- PR에 배포일 표기가 필요한 경우
  ```text
    # <gitmoji> PR 제목
  ```

### ✎ Comment Rule
- Comment의 Resolve 처리
    - 최초 Comment를 작성한 사람이 처리
### ✎ Merge Rule
- PR 머지는 리뷰어가 해주도록 합니다.

2023-05-19 09:42 UTC, leesangb requested changes

2023-05-19 09:42 UTC, leesangb commented on package-lock.json
p1) npm 으로 install 하신것 같아요! yarn 으로 다시 부탁드립니다~

2023-05-19 09:42 UTC, leesangb commented on tt.config.js
p3) config파일이라기보다 스크립트 파일 같은데 root보단 scripts 폴더 만들어서 넣는건 어떨까요?

2023-05-19 10:11 UTC, ixio0330 commented on package-lock.json
패키지 다운이요? 아니면 actions 말씀하시는 건가요?

2023-05-21 11:09 UTC, leesangb commented on package-lock.json
@ixio0330 넵넵 패키지 다운이요! 갑자기 package-lock.json이 추가돼서 npm으로 install 하신것 같아요!

2023-05-25 01:25 UTC, leesangb approved these changes
고생하셨습니다~!!

2023-05-25 01:26 UTC, merged