🚚 moved ui files
sendOwlOrganization/mlab-web pull request #8
Opened 2023-03-19 14:16 UTC by ixio0330

2023-03-19 14:32 UTC, leesangb requested changes

2023-03-19 14:32 UTC, leesangb commented on .vscode/settings.json
> +{
p1) `.vscode`폴더 `.gitignore` 에 추가해주시고 레포에도 삭제해주시면 감사하겠습니다!

2023-03-19 14:32 UTC, leesangb commented on app/layout.tsx
> +import './globals.css'
p1) `prettier`가 제대로 적용되지 않은 것 같습니다. `package.json`에 `init-husky` 실행하셨을까요? 확인 부탁드립니다 🙏

2023-03-22 12:11 UTC, Doodream approved these changes
고생하셨습니다 🙇‍♂️

2023-03-26 13:49 UTC, closed without merging